### PR TITLE
Try to build this on Windows. It should work assuming you have Octave/Matlab, Python3+,

### PR DESCRIPTION
**Pull request by MarquiseRosier**

### CODE REVIEW

**Comment by MarquiseRosier** [comment]
I am working on the scripts so that we can have automated building upon git commits. The CMakeFiles should work though assuming someone has numpy, python3+, octave/matlab, cmake

Finding Python is a bit challenging, I think I am going to inclulde it in our project so that it can be in one place within the project and we don't have to scan for python installations on different systems. This would make the program highly portable. If that is fine with you of course?

We can pretty much have one version of the Python.h, arrayobject.h, ndarrayobject.h, etc etc files and simply have two shared libraries. 1 64 bit and another 32 bit....so that we are saving space when people download our application and making it easy for them to use, What do you think about this?

**Comment by barbua** [comment]
I don't think you should include a Python installation with the project since people that need the Python version should already have their own installation.
If you add any Python files, they might interfere with their own installation. 
It's fine for the users to add the path to their Python by hand. It doesn't have to be all automatic.

**Comment by MarquiseRosier** [comment]
Got it! I will provide the ability for Users to input the location of their Python installation if CMake doesn't find it!! After that we should be pretty much done, the software builds on my Ubuntu, Linux Mint, and Windows 64 box. I will finish setting up Travis CI and AppVeyor to make sure they can build elsewhere. I will also write up a nice little Get Started note in the ReadMe section. This will all be done by next weekend!

**Comment by barbua** [comment]
Sounds great!
Thank you Marquise.

**Pull request merged**
